HW18/config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  # Defines the root path route ("/")
  root 'products#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticate :admin_user do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :products
  resources :categories

  resources :orders, only: %i[index show]
  get '/current_order', to: 'orders#show_current', as: :current_order
  get 'orders/:id/pay_details' => 'orders#pay_details', as: 'order_pay_details'
  put 'orders/:id/pay' => 'orders#pay', as: 'order_pay'
  get 'orders/:id/paid' => 'orders#paid', as: 'order_paid'

  resources :line_items, only: %i[show create update destroy]
  put 'line_items/:id/update_order' => 'line_items#update_order', as: 'line_item_order'
end

HW18/app/models/order.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: orders
#
#  id         :bigint           not null, primary key
#  status     :integer          default("unpaid")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_orders_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Order < ApplicationRecord
  include Orderable

  belongs_to :user
  has_many :line_items, dependent: :destroy

  enum :status, { unpaid: 0, paid: 1 }
end

HW18/app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: %i[show pay_details pay paid]

  def index
    @orders = current_user.orders
  end

  def show
    @line_items = @order.line_items.includes(:product)

    redirect_to order_paid_path if @order.paid?
  end

  def show_current
    @order = current_order
    @line_items = current_order.line_items.includes(:product)
  end

  def pay_details
    @order_id = @order.id if current_user
  end

  def pay
    @order.paid!
    @user_email = current_user.email
    @order_id = @order.id
    UserMailer.new_order(@order.user, @order).deliver_now
    flash[:notice] = 'Thanks So Much for Your Order! I Hope You Enjoy Your New Purchase!'
    redirect_to order_paid_path, method: :get
  end

  def paid; end

  private

  def set_order
    @order = current_user.orders.find(params[:id])
  end
end

HW18/app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
  def order_date(order)
    if order.paid?
      "Date of purchase #{order.updated_at.to_date}"
    else
      "Order date #{order.created_at.to_date}"
    end
  end

  def order_status_view(order)
    if order.paid?
      "Date of purchase #{order.updated_at.to_date}"
    else
      link_to "Order date #{order.created_at.to_date} Please, repeat your order!", root_path
    end
  end

  def order_status_button(order)
    if order.paid?
      link_to 'paid', order_paid_path(order), class: 'btn btn-outline-success btn-sm'
    else
      link_to 'unpaid', order_path(order), class: 'btn btn-outline-danger btn-sm'
    end
  end
end

HW18/app/views/orders/_order_history.html.erb
<table class='table'>
  <tr>
    <th>#</th>
    <th>Image</th>
    <th>Name</th>
    <th>Quantity</th>
    <th>Price</th>
  </tr>
  <% order.line_items.includes(product: :image_attachment).each.with_index do |line_item, index| %>
  <tr>
    <td><%= index+1 %></td>
    <% if line_item.product.image.attached?  %>
      <td><%= image_tag line_item.product.image.variant(:thumb) %> </td>
    <% else %>
      <td><%= image_tag("no_image_thumb.png", alt: 'No Image') %></td>
    <% end %>
    <td><%= line_item.product.name %></td>
    <td><%= line_item.quantity %></td>
    <td><%= number_to_currency(line_item.line_item_total_price) %></td>
  </tr>
  <% end %>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td><b>Total price:</b></td>
    <td><b>
      <%= number_to_currency(order.total_price) %></b></td>
  </tr>
</table>

HW18/app/views/orders/_order_items.html.erb
<table class='table'>
  <tr>
    <th>#</th>
    <th>Image</th>
    <th>Name</th>
    <th>Quantity</th>
    <th>Price</th>
    <th>Delete</th>
  </tr>
  <% @line_items.includes(product: :image_attachment).each.with_index do |line_item, index| %>
  <tr>
    <td><%= index+1 %></td>
    <% if line_item.product.image.attached?  %>
      <td><%= image_tag line_item.product.image.variant(:thumb) %> </td>
    <% else %>
      <td><%= image_tag("no_image_thumb.png", alt: 'No Image') %></td>
    <% end %>
    <td><%= line_item.product.name %></td>
    <td>
      <div class='d-md-flex'>
        <!-- reduce -->
        <%= button_to line_item_order_path(:id => line_item), params: { change_quantity: 'reduce' }, method: :put,
                      class: 'btn btn-outline-danger btn-sm', style: 'padding-left:11px; padding-right:11px;',
                      data: { turbo: false } do %>
          <span><b>-</b></span>
        <% end %>
        <p class='quantity'><%= line_item.quantity %></p>
        <!-- add -->
        <%= button_to line_item_order_path(:id => line_item), params: { change_quantity: 'add' }, method: :put ,
                      class: 'btn btn-outline-success btn-sm', style: 'padding-left:9px; padding-right:9px;',
                      data: { turbo: false } do %>
          <span><b>+</b></span>
        <% end %>
      </div>
    </td>
    <td><%= number_to_currency(line_item.line_item_total_price) %></td>
    <td>
      <!-- Remove -->
      <%= button_to line_item_path(:id => line_item), method: :delete, class: 'btn btn-outline-danger btn-sm' do %>
        <svg xmlns='http://www.w3.org/2000/svg' width='12' height='12' fill='currentColor' class='bi bi-trash3-fill' viewBox='0 0 16 16'>
          <path d='M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z'/>
        </svg>
      <% end %>
    </td>
  </tr>
  <% end %>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td><b>Total price:</b></td>
    <td><b><%= number_to_currency @order.total_price %></b></td>
  </tr>
</table>

HW18/app/views/orders/index.html.erb
<h2 class='mt-4'><svg xmlns='http://www.w3.org/2000/svg' width='48' height='48' fill='currentColor' class='bi bi-bag-heart-fill' viewBox='0 0 16 16'>
  <path d='M11.5 4v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5ZM8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1Zm0 6.993c1.664-1.711 5.825 1.283 0 5.132-5.825-3.85-1.664-6.843 0-5.132Z'/>
</svg>
  History of your orders:</h2>
<div class='mt-3'>
  <% @orders.each do |order| %>
    <h5>Order # <%= order.id %></h5>
    <span><%= order_date(order) %></span>
    <span class='ms-3'><%= order_status_button(order) %></span>
    <br>
    <%= render partial: 'order_history', locals: { order: order } %>
  <% end %>
</div>

HW18/app/views/orders/paid.html.erb
<h5 class='mt-4'><svg xmlns='http://www.w3.org/2000/svg' width='48' height='48' fill='currentColor' class='bi bi-bag-check-fill' viewBox='0 0 16 16'>
  <path fill-rule='evenodd' d='M10.5 3.5a2.5 2.5 0 0 0-5 0V4h5v-.5zm1 0V4H15v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4h3.5v-.5a3.5 3.5 0 1 1 7 0zm-.646 5.354a.5.5 0 0 0-.708-.708L7.5 10.793 6.354 9.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z'/>
</svg>
  <i>Details of your order:</i></h5>
<h3>Order #<%= @order.id %></h3>
<%= order_status_view(@order) %>
<div class='mt-3'>
  <%= render partial: 'order_history', locals: { order: @order } %>
</div>

HW18/app/views/orders/pay_details.html.erb
<h1 class='mt-4'>Order # <%= @order_id %></h1>
<div class='address'>
  <h1><svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi bi-envelope"
           viewBox="0 0 16 16">
    <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2
          7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64
          3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z"/>
  </svg>
    Add address</h1>
  <%= form_tag({controller: 'orders', action: 'pay'}, method: :put, id: 'simplify-address-form') do %>
    <div class='mt-3'>
      <%= label_tag('fullname', 'Full Name (First and Last name):') %><br>
      <%= text_field_tag('fullname', nil, size: 45, autocomplete: 'on', autofocus: true, :required => true) %>
    </div>
    <div class='mt-3'>
      <%= label_tag('country', 'Country:') %><br>
      <%= text_field_tag('country', nil, size: 45, autocomplete: 'on', :required => true) %>
    </div>
    <div class='mt-3'>
      <%= label_tag('address', 'Address:') %><br>
      <%= text_field_tag('address', nil, size: 45, autocomplete: 'on', :placeholder => 'Street address or P.O.Box') %><br>
      <%= text_field_tag('address', nil, size: 45, autocomplete: 'on', :placeholder => 'Apt, suite, unit, building, floor etc') %>
    </div>
    <div class='mt-3'>
      <%= label_tag('city', 'City:') %>
      <%= text_field_tag('city', nil, size: 26, autocomplete: 'on', :required => true) %>
      <%= label_tag('pin', 'ZIP:') %>
      <%= text_field_tag('pin', nil, size: 6, autocomplete: 'on') %>
    </div>
    <div class='mt-3 me-0 ms-0 mb-4'>
      <%= label_tag('region', 'Region:') %>
      <%= text_field_tag('region', nil, size: 17, autocomplete: 'on') %>
      <%= label_tag('phone', 'Phone:') %>
      <%= text_field_tag('phone', nil, size: 10, autocomplete: 'on',
                         :pattern => '+[0-9]{3}-[0-9]{2}-[0-9]{3}-[0-9]{2}-[0-9]{2}',
                         :placeholder => '+380-00-000-00-00', :required => true) %>
    </div>
  <% end %>
</div>
<div class="payment-title">
  <h1><svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor"
           class="bi bi-credit-card-2-front" viewBox="0 0 16 16">
    <path d="M14 3a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h12zM2 2a2 2 0 0 0-2 2v8a2 2 0 0 0 2
             2h12a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H2z"/>
    <path d="M2 5.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-1zm0 3a.5.5 0 0 1
             .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5zm3
             0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0
             1-.5-.5zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5z"/>
  </svg>
    Payment Information</h1>
  <h5>Payment amount <%= number_to_currency @order.total_price %></h5>
</div>
<%= form_tag({controller: 'orders', action: 'pay'}, method: :put, id: 'simplify-payment-form') do %>
  <div>
    <%= label_tag('cardnumber', 'Credit Card Number:') %>
    <%= text_field_tag('cardnumber', nil, maxlength: 16, autocomplete: 'off', autofocus: true,
                       :pattern => '[0-9]{4}[0-9]{4}[0-9]{4}[0-9]{4}', :placeholder => '0000 0000 0000 0000',
                       :required => true) %>
  </div>
  <div>
    <%= label_tag('expirationdate', 'Expiry Date:') %>
    <%= select_month(Date.new(Date.today.year, 1).beginning_of_month, {use_two_digit_numbers: true},
                     {id: 'expirationmonth'}) %>
    <%= select_year(Date.today, {start_year: Date.today.year, end_year: Date.today.year+10}, {id: 'expirationyear'}) %>
    <%= label_tag('securitycode', 'CVC:') %>
    <%= text_field_tag('securitycode', nil, size: 3, autocomplete: 'off', :pattern => '[0-9]{3}',
                       :placeholder => '000', :required => true) %>
  </div>
  <%= button_to order_pay_path, method: :put, class: 'btn btn-outline-primary' do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-coin"
         viewBox="0 0 16 16">
      <path d="M5.5 9.511c.076.954.83 1.697 2.182 1.785V12h.6v-.709c1.4-.098 2.218-.846 2.218-1.932 0-.987-.626-1.496-
               1.745-1.76l-.473-.112V5.57c.6.068.982.396 1.074.85h1.052c-.076-.919-.864-1.638-2.126-1.716V4h-.6v.719c-
               1.195.117-2.01.836-2.01 1.853 0 .9.606 1.472 1.613 1.707l.397.098v2.034c-.615-.093-1.022-.43-1.114-.9H5.
               5zm2.177-2.166c-.59-.137-.91-.416-.91-.836 0-.47.345-.822.915-.925v1.76h-.005zm.692 1.193c.717.166 1.048.
               435 1.048.91 0 .542-.412.914-1.135.982V8.518l.087.02z"/>
      <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
      <path d="M8 13.5a5.5 5.5 0 1 1 0-11 5.5 5.5 0 0 1 0 11zm0 .5A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"/>
    </svg>
    Process Payment
  <% end %>
<% end %>

HW18/app/views/orders/show.html.erb
<h1  class='mt-4'> <svg xmlns='http://www.w3.org/2000/svg' width='48' height='48' fill='currentColor' class='bi bi-bookmark-check-fill' viewBox='0 0 16 16'>
  <path fill-rule='evenodd' d='M2 15.5V2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.74.439L8 13.069l-5.26 2.87A.5.5 0 0 1 2 15.5zm8.854-9.646a.5.5 0 0 0-.708-.708L7.5 7.793 6.354 6.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z'/>
</svg>
  Order #<%= @order.id %></h1>
<%= render partial: "order_items" %>
<%= button_to order_pay_details_path, method: :get, class: 'btn btn-outline-primary' do %>
  <svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' class='bi bi-credit-card-2-front-fill' viewBox='0 0 16 16'>
    <path d='M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2.5 1a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h2a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-2zm0 3a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zm0 2a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1h-1zm3 0a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1h-1zm3 0a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1h-1zm3 0a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1h-1z'/>
  </svg>
  Proceed to Buy
<% end %>

HW18/app/views/orders/show_current.html.erb
<h1 class='mt-4'><svg xmlns='http://www.w3.org/2000/svg' width='48' height='48' fill='currentColor' class='bi bi-cart4' viewBox='0 0 16 16'>
  <path d='M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z'/>
</svg>
  Your Cart</h1>
<% if @line_items.exists? %>
  <%= render partial: "order_items" %>
  <%= button_to order_pay_details_path(@order), method: :get, class: 'btn btn-outline-primary' do %>
    <svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' class='bi bi-bookmark-check-fill' viewBox='0 0 16 16'>
      <path fill-rule='evenodd' d='M2 15.5V2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.74.439L8 13.069l-5.26 2.87A.5.5 0 0 1 2 15.5zm8.854-9.646a.5.5 0 0 0-.708-.708L7.5 7.793 6.354 6.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z'/>
    </svg>
    Checkout
  <% end %>
<% else %>
  <p class='mt-4 ms-4'>Your cart is empty</p>
<% end %>