HW18/config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  # Defines the root path route ("/")
  root 'products#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticate :admin_user do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :products
  resources :categories

  resources :orders, only: %i[index show]
  get '/current_order', to: 'orders#show_current', as: :current_order
  get 'orders/:id/pay_details' => 'orders#pay_details', as: 'order_pay_details'
  put 'orders/:id/pay' => 'orders#pay', as: 'order_pay'
  get 'orders/:id/paid' => 'orders#paid', as: 'order_paid'

  resources :line_items, only: %i[show create update destroy]
  put 'line_items/:id/update_order' => 'line_items#update_order', as: 'line_item_order'
end

HW18/app/models/product.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: products
#
#  id          :bigint           not null, primary key
#  description :text
#  name        :string
#  price       :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint           not null
#
# Indexes
#
#  index_products_on_category_id  (category_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#
class Product < ApplicationRecord
  belongs_to :category
  has_many :line_items, dependent: :nullify
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
    attachable.variant :main, resize_to_limit: [502, 378]
  end

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  broadcasts_to ->(_product) { 'products' }, inserts_by: :prepend
end

HW18/app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show]

  def index
    @products = Product.all.with_attached_image
  end

  def show
    @breadcrumb = @product.category
    @product
  end

  private

  def set_product
    @product = Product.with_attached_image.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :image)
  end
end

HW18/app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
  def add_cart(product)
    turbo_frame_tag dom_id(product) do
      if current_order.line_items.where(product_id: product.id).present?
        render partial: 'products/in_cart', locals: { product: }
      else
        render partial: 'products/add_cart', locals: { product: }
      end
    end
  end
end

HW18/app/views/products/_add_cart.html.erb
<%= button_to line_items_path(product_id: product.id), class: 'btn btn-danger btn-sm' do %>
  Add
  <svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' class='bi bi-cart4'
       viewBox='0 0 16 16'>
    <path
      d='M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z'/>
  </svg>
<% end %>

HW18/app/views/products/_in_cart.html.erb
<%= link_to current_order_path, class: 'btn btn-success btn-sm', style: 'margin-right:11px;' do %>
  In
  <svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' class='bi bi-cart4' viewBox='0 0 16 16'>
       <path d='M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z'/>
  </svg>
<% end %>

HW18/app/views/products/_product.html.erb
<div class="col-auto">
  <div class='card p-0 mt-3 mx-auto shadow-sm'>
    <% if product.image.attached? %>
      <%= image_tag product.image.variant(:main), alt: product.name %>
    <% else %>
      <%= image_tag("no_image.png", alt: 'No image') %>
    <% end %>
    <div class='card-body'>
      <h5 class='card-title text-center'><%= link_to product.name, product %></h5>
      <p class='card-price mt-auto text-end'><%= number_to_currency(product.price) %></p>
      <%#= add_cart(product) if current_user %>
      <%= turbo_frame_tag dom_id(product) do %>
        <%# if !current_order.line_items.where(product_id: product.id).present? %>
          <%= button_to line_items_path(product_id: product.id), class: 'btn btn-danger btn-sm' do %>
            Add
            <svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' class='bi bi-cart4'
                 viewBox='0 0 16 16'>
            <path
              d='M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z'/>
            </svg>
          <% end %>
        <%# else %>
          <%#= link_to current_order_path, class: 'btn btn-success btn-sm', style: 'margin-right:11px;' do %>
<!--            In-->
<!--            <svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' class='bi bi-cart4' viewBox='0 0 16 16'>-->
<!--              <path d='M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z'/>-->
<!--            </svg>-->
          <%# end %>
        <%# end %>
      <% end %>
    </div>
  </div>
</div>

HW18/app/views/products/index.html.erb
<%= turbo_stream_from 'products' %>
<div id='viewport'>
  <!-- Content -->
  <div id='content'>
    <div class='container-fluid'>
      <div id="products" class="row products">
        <div class='row g-5 justify-content-center align-items-center vh-100 flex-wrap'>
          <% @products.each do |product| %>
            <%= render partial: 'products/product', locals: { product: product } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

HW18/app/views/products/show.html.erb
<div class='row mt-3'>
  <nav aria-label='breadcrumb'>
    <ol class='breadcrumb'>
      <li class='breadcrumb-item'><%= link_to 'Home', root_path %></li>
      <li class='breadcrumb-item'><%= link_to @product.category.title, @product.category %></li>
      <li class='breadcrumb-item active' aria-current='page'><%= @product.name %></li>
    </ol>
  </nav>
</div>
<div class='card mb-3' style='max-width: 1200px;'>
  <div class='row g-0'>
    <div class='col-md-4'>
      <% if @product.image.attached?  %>
        <%= image_tag @product.image.variant(:main), class: 'img-fluid rounded-start', alt: @product.name %>
      <% else %>
        <%= image_tag("no_image.png", class: 'card-img-top', alt: 'No Image') %>
      <% end %>
    </div>
    <div class='col-md-8'>
      <div class='card-body'>
        <h3 class='text-center'><%= @product.name %></h3>
        <p class='card-text'><%= @product.description %></p>
        <p class='text-end'><i>Category: <%= @product.category.title %></i></p>
        <p class='card-text'><h4 style='color:#d63384; text-align:right'>Price: <%= number_to_currency(@product.price) %></h4></p>
        <%= turbo_frame_tag dom_id(@product) do %>
          <%= button_to line_items_path(product_id: @product.id), class: 'btn btn-danger btn-sm' do %>
            Add
            <svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' class='bi bi-cart4' viewBox='0 0 16 16'>
              <path d='M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z'/>
            </svg>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>